#!/usr/bin/env bash
# Provision disposable local AgentForge dependencies and write .env.local.
# This script is for development/testing only; never use its credentials in production.
set -Eeuo pipefail

umask 077

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE="${AGENTFORGE_ENV_FILE:-$ROOT_DIR/.env.local}"

log() { printf '\n==> %s\n' "$*"; }
die() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

have docker || die "Docker is not installed."
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is not available."
[[ -f "$ROOT_DIR/docker-compose.yml" ]] || die "docker-compose.yml not found in $ROOT_DIR"

if [[ -e "$ENV_FILE" ]]; then
  die "$ENV_FILE already exists. Move it aside before rerunning this bootstrap."
fi

log "Checking Docker Engine access"
docker info >/dev/null 2>&1 || die \
  "Docker Engine is not accessible. Add this user to the docker group, start a new login session, and retry."

log "Starting PostgreSQL and MinIO"
docker compose up -d postgres minio

log "Waiting for PostgreSQL"
postgres_ready=0
for _ in $(seq 1 60); do
  if docker compose exec -T postgres pg_isready -U agentforge >/dev/null 2>&1; then
    postgres_ready=1
    break
  fi
  sleep 1
done
(( postgres_ready == 1 )) || die "PostgreSQL did not become ready."

log "Waiting for MinIO"
minio_ready=0
for _ in $(seq 1 60); do
  if curl -fsS http://127.0.0.1:9000/minio/health/live >/dev/null 2>&1; then
    minio_ready=1
    break
  fi
  sleep 1
done
(( minio_ready == 1 )) || die "MinIO did not become ready."

log "Ensuring the development MinIO bucket exists"
# The compose credentials are intentionally disposable development credentials.
# Use an explicitly supplied host client so bootstrap never pulls an unapproved mc image.
mc_bin="${AGENTFORGE_MC_BIN:-$(command -v mc || true)}"
[[ -n "$mc_bin" && -x "$mc_bin" ]] || die \
  "MinIO client is required; set AGENTFORGE_MC_BIN to a trusted mc executable."
MC_CONFIG_DIR="${AGENTFORGE_MC_CONFIG_DIR:-$ROOT_DIR/.agentforge-mc}" \
  "$mc_bin" alias set local http://127.0.0.1:9000 agentforge agentforge-dev-only >/dev/null
MC_CONFIG_DIR="${AGENTFORGE_MC_CONFIG_DIR:-$ROOT_DIR/.agentforge-mc}" \
  "$mc_bin" mb --ignore-existing local/agentforge >/dev/null

random_hex() { openssl rand -hex "$1"; }
random_uuid() { cat /proc/sys/kernel/random/uuid; }

api_key="af_live_$(random_hex 24)"
worker_token="$(random_hex 32)"
tenant_id="$(random_uuid)"
guest_secret="$(random_hex 32)"

firecracker_bin="${AGENTFORGE_FIRECRACKER_BIN:-}"
firecracker_kernel="${AGENTFORGE_KERNEL:-}"
firecracker_rootfs="${AGENTFORGE_ROOTFS:-}"

if [[ -n "$firecracker_bin" ]]; then
  [[ -x "$firecracker_bin" ]] || die "AGENTFORGE_FIRECRACKER_BIN is not executable: $firecracker_bin"
fi
if [[ -n "$firecracker_kernel" ]]; then
  [[ -r "$firecracker_kernel" ]] || die "AGENTFORGE_KERNEL is not readable: $firecracker_kernel"
fi
if [[ -n "$firecracker_rootfs" ]]; then
  [[ -r "$firecracker_rootfs" ]] || die "AGENTFORGE_ROOTFS is not readable: $firecracker_rootfs"
fi

log "Writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-local-services.sh. Do not commit or share.
AGENTFORGE_RUNTIME=docker
AGENTFORGE_BIND=127.0.0.1:8080

DATABASE_URL=postgresql://agentforge:agentforge-dev-only@127.0.0.1:5432/agentforge
AGENTFORGE_TENANT_ID=$tenant_id
AGENTFORGE_API_KEY=$api_key
AGENTFORGE_WORKER_TOKEN=$worker_token

AGENTFORGE_S3_ENDPOINT=http://127.0.0.1:9000
AGENTFORGE_S3_REGION=us-east-1
AGENTFORGE_S3_BUCKET=agentforge
AGENTFORGE_S3_ACCESS_KEY_ID=agentforge
AGENTFORGE_S3_SECRET_ACCESS_KEY=agentforge-dev-only

# Optional Firecracker test artifacts. Empty values mean Firecracker tests remain blocked.
AGENTFORGE_FIRECRACKER_BIN=$firecracker_bin
AGENTFORGE_KERNEL=$firecracker_kernel
AGENTFORGE_ROOTFS=$firecracker_rootfs
AGENTFORGE_GUEST_SECRET=$guest_secret
EOF
chmod 600 "$ENV_FILE"

log "Bootstrap complete"
printf 'Environment file: %s\n' "$ENV_FILE"
printf 'PostgreSQL:       postgresql://agentforge:agentforge-dev-only@127.0.0.1:5432/agentforge\n'
printf 'MinIO:            http://127.0.0.1:9000\n'
printf 'API key:          %s\n' "$api_key"
printf 'Worker token:     %s\n' "$worker_token"
printf 'Tenant ID:        %s\n' "$tenant_id"
printf '\nLoad it before starting AgentForge:\n'
printf '  set -a; source %q; set +a\n' "$ENV_FILE"

if [[ ! -e /dev/kvm ]]; then
  printf '\nWARNING: /dev/kvm is unavailable; Firecracker tests remain blocked.\n'
elif [[ ! -r /dev/kvm || ! -w /dev/kvm ]]; then
  printf '\nWARNING: current user cannot read/write /dev/kvm; add the user to the kvm group and start a new login session.\n'
fi

if [[ -z "$firecracker_bin" || -z "$firecracker_kernel" || -z "$firecracker_rootfs" ]]; then
  cat <<'EOF'

Firecracker prerequisites are incomplete.
To enable Firecracker tests, set these before rerunning the script:

  export AGENTFORGE_FIRECRACKER_BIN=/opt/firecracker/firecracker
  export AGENTFORGE_KERNEL=/var/lib/agentforge/images/vmlinux
  export AGENTFORGE_ROOTFS=/var/lib/agentforge/images/agentforge-rootfs.ext4
EOF
fi
